#ifndef SERVERTERMS
#define SERVERTERMS


#define INITIAL_PROMPT "Welcome to Abhay Bhadouriya International bank of IIITB!\n\nWho are you?\n-------------------------------------------------------------\n1. Admin\n2. Customer\n3. Manager\n4. Employee\n-------------------------------------------------------------\n\nPress any other number to exit\nEnter the number corresponding to the choice!"

// ========== COMMON TEXT =============================

// LOGIN
#define ENTER_LOGIN_ID "Enter your login ID"
#define ENTER_PASSWORD "Enter your password \n# "
#define INVALID_LOGIN "The login ID specified doesn't exist!$"
#define INVALID_PASSWORD "The password specified doesn't match!$"
#define SALT_BAE "MT2024003"
 
// GET ACCOUNT DETAILS
#define GET_ACCOUNT_NUMBER "Enter the account number of the account you're searching for"
#define GET_CUSTOMER_ID "Enter the customer ID of the customer you're searching for"

#define ERRON_INPUT_FOR_NUMBER "Need integer you passed some other charactor\nYou'll now be redirected to the main menu!^"

#define INVALID_MENU_CHOICE "It seems you've made an invalid menu choice\nYou'll now be redirected to the main menu!^"

#define CUSTOMER_ID_DOESNT_EXIT "No customer could be found for the given ID"
#define CUSTOMER_LOGIN_ID_DOESNT_EXIT "No customer could be found for the given login ID$"
#define EMPLOYEE_LOGIN_ID_DOESNT_EXIT "No Employee could be found for the given login ID$"
#define ACCOUNT_ID_DOESNT_EXIT "No account could be found for the given account number"

#define TRANSACTIONS_NOT_FOUND "No transactions were performed on this account by the customer!^"

#define GET_BALANCE "Account Balance : "

#define LOAN_APPLICATION_APPLIED "Follow Applications are applied by the customer"
// ====================================================

// ========== ADMIN SPECIFIC TEXT======================

// LOGIN WELCOME
#define ADMIN_LOGIN_WELCOME "Welcome great Lord Abhay Bhadouriya!\nYou are admin of this bank so use your powers responsibly!\nPlease provide your security Code to access it!"
#define ADMIN_LOGIN_SUCCESS "Welcome back The Great Great Abhay Bhadouriya!"

// ADMIN MENU
#define ADMIN_MENU "1. Get customer Account\n2. Add customer Account\n3. Modify\n4. View Employee List\n5. Add Employee\n6. Remove Emp\\Customer  \n7. View Managers List\n8. Password Change\n9. Logout\nPress any other key to logout"

// DELETE ACTIVATE DEACTIVATE ACCOUNT
#define ADMIN_WHO_TO_DEACT_ACT "Who do you want to Activate/Deactivate\n\t1. Customer\n\t2. Manager \n\t3. Employee"
#define ADMIN_DEACT_NOTIFY "This account is currently Active you want it to Deactivate\n(After this user will not able to login)\n\n\t1. Press 1 to Deactivate\n\t2. Press 2 to return to Main Menu"
#define ADMIN_ACT_NOTIFY "This account is currently Deactivated you want it to Activate\n(After this user will able to login)\n\n\t1. Press 1 to Activate\n\t2. Press 2 to return to Main Menu"

// ADD CUSTOMER
#define ADMIN_ADD_CUSTOMER_NAME "What is the customer's name?"
#define ADMIN_ADD_CUSTOMER_GENDER "What is the customer's gender?\nEnter M for male, F for female and O for others"
#define ADMIN_ADD_CUSTOMER_AGE "What is the customer's age?"
#define ADMIN_ADD_CUSTOMER_AUTOGEN_LOGIN "The autogenerated login ID for the customer is : "
#define AUTOGEN_PASSWORD "abhaytheBoss" // append to end of next string macro
#define ADMIN_ADD_CUSTOMER_AUTOGEN_PASSWORD "The autogenerated password for the customer is : "
#define ADMIN_ADD_CUSTOMER_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"

//ADD EMPLOYEE
#define ADMIN_ADD_EMPLOYEE_NAME "What is the Employee Name?"
#define ADMIN_ADD_EMPLOYEE_GENDER "What is the Employee Gender?"
#define ADMIN_ADD_EMPLOYEE_AGE "What is the Employee Age?"
#define ADMIN_ADD_AUTOGENERATED_ID "The autogenerated Login ID of this Employee is : "
#define ADMIN_ADD_PASSWORD "abhay123"
#define ADMIN_ADD_EMPLOYEE_AUTOGEN_PASSWORD "The autogenerated password for the Employee is : "
#define ADMIN_ADD_CUSTOMER_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"
#define ADMIN_ADD__EMPLOYEE_ROLE "Enter Employee Role\nPress 1 for Manager\nPress 2 for Employee"

// ADD ACCOUNT
#define ADMIN_ADD_ACCOUNT_NUMBER "The newly created account's number is :"


// ADD FEEDBACK 
#define CUSTOMER_FEEDBACK "Write your Feedback\n"
#define CUSTOMER_LOAN_MENU "Welcome to Abhay Bhadouriya International bank of IIITB Loan services.\n\t1. Apply Loan\n\t2. Loan Status"
#define CUSTOMER_LOAN_APPLY "Enter your desired ammount you want to apply : \n"
#define CUSTOMER_LOAN_APPLIED "Thanks for opting the Abhay Bhadouriya International bank of IIITB Loan services. your loan requested is submitted."
// DELETE ACCOUNT
#define ADMIN_DEL_ACCOUNT_NO "What is the account number of the account you want to delete?"
#define ADMIN_DEL_ACCOUNT_SUCCESS "This account has been successfully deleted\nRedirecting you to the main menu ...^"
#define ADMIN_DEL_ACCOUNT_FAILURE "This account cannot be deleted since it still has some money\nRedirecting you to the main menu ...^"

#define ADMIN_DEL_EMPLOYEE_NO "What is the Employee ID of Employee you want to remove?"
#define ADMIN_DEL_EMPLOYEE_SUCCESS "This Employee has been successfully removed\nNow he/she not able to access his/her account\nRedirecting you to the main menu ...^"

#define ADMIN_DEL_MANAGER_NO "What is the Manager ID of Manager you want to remove?"
#define ADMIN_DEL_MANAGER_SUCCESS "This Manager has been successfully removed\nNow he/she not able to access his/her account\nRedirecting you to the main menu ...^"


#define ADMIN_MODIFY_PROMPT "Please select whose details you want to update?\n\t1. Customer\n\t2. Employee/Manager"
#define ADMIN_GET_UNIQUE_ID "Enter Unique ID of USER"
// MODIFY CUSTOMER INFO
#define ADMIN_MOD_CUSTOMER_ID "Enter the ID of the customer who's information you want to edit"
#define ADMIN_MOD_EMPLOYEE_MENU "Which information would you like to modify?\n\t1. Name\n\t 2. Age\n\t 3. Gender\n\t 4. Role \nPress any other key to cancel"
#define ADMIN_MOD_CUSTOMER_MENU "Which information would you like to modify?\n\t1. Name\n\t 2. Age\n\t 3. Gender\nPress any other key to cancel"

#define ADMIN_MOD_CUSTOMER_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_CUSTOMER_NEW_GENDER "What's the updated value for gender?"
#define ADMIN_MOD_CUSTOMER_NEW_AGE "What's the updated value for age?"

#define ADMIN_MOD_CUSTOMER_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"

#define ADMIN_LOGOUT "Logging you out now superman! Good bye!$"

// MODIFY EMPLOYEE INFO
#define ADMIN_MOD_EMPLOYEE_ID "Enter the ID of the customer who's information you want to edit"
// #define ADMIN_MOD_EMPLOYEE_MENU "Which information would you like to modify?\n1. Name 2. Age 3. Gender 4. Role \nPress any other key to cancel"
#define ADMIN_MOD_EMPLOYEE_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_EMPLOYEE_NEW_GENDER "What's the updated value for gender?"
#define ADMIN_MOD_EMPLOYEE_NEW_AGE "What's the updated value for age?"

#define ADMIN_MOD_CUSTOMER_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"

// MANAGER MENU

#define MANAGER_MENU "Hello Manager\n1. Activate/Deactivate Account\n2. Assign Loan\n3. Review FeedBack\n4. ChangePassword \n5. Logout"
#define MANAGER_ACT_DEACT_ACC "Enter the Account number  you want to perform Activate/Deactivate Account:"
#define MANAGER_ASSIGN_LOAN_MENU "LOAN MENU\n1. Approved Loans\n2. Pending Loans to take Action\n3. In Process Loans"
#define MANAGER_ACC "Enter the Loan Account Number"
#define MANAGER_EMP "Enter the Employee number"
#define ENTER_NEW_PASSWORD "Enter new password"
// ====================================================

//EMPLOYEE
#define EMPLOYEE_MENU "Hello Employee\n\t"\
                      "1. Add Customer\n\t"\
                      "2. Modify Customer Detials\n\t"\
                      "3. Process Assigned Loan\n\t"\
                      "4. Approve/Reject Loans\n\t"\
                      "5. View assigned Loans\n\t"\
                      "6. Customer Transections\n\t"\
                      "7. Change Password\n\t"\
                      "8. Logout\n"
#define MENU_ADD_NEW_CUSTOMER "Add New Customer"
#define MENU_MODIFY_CUSTOMER_DETAILS "Modify Customer Details"
#define MENU_PROCESS_LOAN_APPLICATIONS "Process Loan Applications"
#define MENU_APPROVE_REJECT_LOANS "Approve/Reject Loans"
#define MENU_VIEW_ASSIGNED_LOAN_APPLICATIONS "View Assigned Loan Applications"
#define MENU_ENTER_LOAN_NUMBER "Enter Loan account Number which you want to work"
#define MODIFY_SUCCESS = "User Details updated succesfully"
#define MODIFY_FAILURE = "User Details updation Failed try Again"
#define MENU_VIEW_CUSTOMER_TRANSACTIONS "View Customer Transactions (Passbook)"
#define MENU_CHANGE_PASSWORD "Change Password"
#define MENU_LOGOUT "Logout"
#define MENU_EXIT "Exit"


// login
#define EMPLOYEE_LOGIN_WELCOME "Welcome dear Employee! Enter your credentials to gain access to your account!"
//===========================================




// ========== CUSTOMER SPECIFIC TEXT===================

// LOGIN WELCOME
#define CUSTOMER_LOGIN_WELCOME "Welcome dear customer! Enter your credentials to gain access to your account!"
#define CUSTOMER_LOGIN_SUCCESS "Welcome beloved customer!"
#define CUSTOMER_ALREADY_LOGGED_IN "You are already Logged-In \nPlease Try again after some time"
#define CUSTOMER_LOGOUT "Logging you out now dear customer! Good bye!$"

// ADMIN MENU
#define CUSTOMER_MENU "1. Get Customer Details\n2. Deposit Money\n3. Withdraw Money\n4. Get Balance\n5. Get Transaction information\n6. Change Password\n7. Transfer Money\n8. Add FeedBack\n9 Apply Loan\n10. Logout"

#define ACCOUNT_DEACTIVATED "It seems your account has been deactivated!^"

#define DEPOSIT_AMOUNT "How much is it that you want to add into your bank?"
#define DEPOSIT_AMOUNT_INVALID "You seem to have passed an invalid amount!^"
#define DEPOSIT_AMOUNT_SUCCESS "The specified amount has been successfully added to your bank account!^"

#define TRANSFER_AMOUNT "How much you want to transfer from your bank?"
#define TRANSFER_AMOUNT_INVALID "You seem to have passed an invalid amount!^"
#define TRANSFER_AMOUNT_SUCCESS "The specified amount has been successfully Transfered from your bank account!^"
#define TRANSFER_ACCOUNT_ID "Enter the Account number you want to send the money!^"
#define TRANSFER_ACCOUNT_INVALID "Your entered account is not valid please enter valid account number!^"

#define LOAN_APPLY "how much Loan money you want to apply for"
#define LOAN_GET_DETAIL "Following are the Loans you applied"
#define LOAN_MENU "LOAN Menu \n1. Apply\n2. View Loan Applications"



#define WITHDRAW_AMOUNT "How much is it that you want to withdraw from your bank?"
#define WITHDRAW_AMOUNT_INVALID "You seem to have either passed an invalid amount or you don't have enough money in your bank to withdraw the specified amount^"
#define WITHDRAW_AMOUNT_SUCCESS "The specified amount has been successfully withdrawn from your bank account!^"

#define PASSWORD_CHANGE_OLD_PASS "Enter your old password"
#define PASSWORD_CHANGE_OLD_PASS_INVALID "The entered password doesn't seem to match with the old password"
#define PASSWORD_CHANGE_NEW_PASS "Enter the new password"
#define PASSWORD_CHANGE_NEW_PASS_RE "Reenter the new password"
#define PASSWORD_CHANGE_NEW_PASS_INVALID "The new password and the reentered passwords don't seem to pass!^"
#define PASSWORD_CHANGE_SUCCESS "Password successfully changed!^"

// ====================================================

#define ERROR_CLOSE "10122000"

#define ACCOUNT_FILE "./database/account.abhay.bank"
#define LOAN_FILE "./database/loan.abhay.bank"
#define TRANSACTION_FILE "./database/transactions.abhay.bank"
#define EMPLOYEE_FILE "./database/employee.abhay.bank"
#define FEEDBACK_FILE "./database/Feedback.abhay.bank"

// #include "../recordStruct/structs.h"

//------------TYPE DEFINE
#define ADMIN_TYPE 1
#define CUSTR_TYPE 2
#define EMPLY_TYPE 3

//------------Type Transections
#define TRANSACTION_TYPE_WITHDRAW 1
#define TRANSACTION_TYPE_DEPOSIT 2
#define TRANSACTION_TYPE_TRANSFER 3
#define TRANSACTION_TYPE_LOANCREDIT 4
#endif